version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: deal-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
